version: '3.1'

services:
  dw-mysql:
    image: mysql:8.0.29-debian
    container_name: dw_mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
      - TZ=America/Sao_Paulo
    ports:
      - $DB_PORT:3306
    volumes:
      - ./mysql:/var/lib/mysql
